# Generated by Django 3.0.8 on 2020-07-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200714_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='service',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='userid',
        ),
    ]
