# Generated by Django 3.0.8 on 2020-07-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20200714_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='order_status',
            field=models.CharField(choices=[('1', 'Request Generated'), ('2', 'Request Accepted'), ('3', 'Staff Allocated'), ('4', 'On The Way'), ('5', 'Incomplete'), ('6', 'Completed')], default='2', max_length=1),
        ),
    ]
